/* Generated By:JJTree: Do not edit this line. /home/egonw/var/Projects/SourceForge/git-svn/cdk/src/main/org/openscience/cdk/smiles/smarts/parser/SMARTSParserTreeConstants.java */

package org.openscience.cdk.smiles.smarts.parser;

/** 
*
* @cdk.module smarts 
*/

public interface SMARTSParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTREACTION = 1;
  public int JJTGROUP = 2;
  public int JJTSMARTS = 3;
  public int JJTATOM = 4;
  public int JJTLOWANDBOND = 5;
  public int JJTORBOND = 6;
  public int JJTEXPLICITHIGHANDBOND = 7;
  public int JJTIMPLICITHIGHANDBOND = 8;
  public int JJTNOTBOND = 9;
  public int JJTSIMPLEBOND = 10;
  public int JJTEXPLICITATOM = 11;
  public int JJTLOWANDEXPRESSION = 12;
  public int JJTOREXPRESSION = 13;
  public int JJTEXPLICITHIGHANDEXPRESSION = 14;
  public int JJTIMPLICITHIGHANDEXPRESSION = 15;
  public int JJTNOTEXPRESSION = 16;
  public int JJTRECURSIVESMARTSEXPRESSION = 17;
  public int JJTVOID = 18;
  public int JJTTOTALHCOUNT = 19;
  public int JJTIMPLICITHCOUNT = 20;
  public int JJTEXPLICITCONNECTIVITY = 21;
  public int JJTATOMICNUMBER = 22;
  public int JJTHYBRDIZATIONNUMBER = 23;
  public int JJTCHARGE = 24;
  public int JJTRINGCONNECTIVITY = 25;
  public int JJTPERIODICGROUPNUMBER = 26;
  public int JJTTOTALCONNECTIVITY = 27;
  public int JJTVALENCE = 28;
  public int JJTRINGMEMBERSHIP = 29;
  public int JJTSMALLESTRINGSIZE = 30;
  public int JJTALIPHATIC = 31;
  public int JJTNONCHHEAVYATOM = 32;
  public int JJTAROMATIC = 33;
  public int JJTANYATOM = 34;
  public int JJTATOMICMASS = 35;
  public int JJTRINGIDENTIFIER = 36;
  public int JJTCHIRALITY = 37;
  public int JJTELEMENT = 38;


  public String[] jjtNodeName = {
    "Start",
    "Reaction",
    "Group",
    "Smarts",
    "Atom",
    "LowAndBond",
    "OrBond",
    "ExplicitHighAndBond",
    "ImplicitHighAndBond",
    "NotBond",
    "SimpleBond",
    "ExplicitAtom",
    "LowAndExpression",
    "OrExpression",
    "ExplicitHighAndExpression",
    "ImplicitHighAndExpression",
    "NotExpression",
    "RecursiveSmartsExpression",
    "void",
    "TotalHCount",
    "ImplicitHCount",
    "ExplicitConnectivity",
    "AtomicNumber",
    "HybrdizationNumber",
    "Charge",
    "RingConnectivity",
    "PeriodicGroupNumber",
    "TotalConnectivity",
    "Valence",
    "RingMembership",
    "SmallestRingSize",
    "Aliphatic",
    "NonCHHeavyAtom",
    "Aromatic",
    "AnyAtom",
    "AtomicMass",
    "RingIdentifier",
    "Chirality",
    "Element",
  };
}
