/* Generated By:JavaCC: Do not edit this line. NomParserConstants.java */
/*
 *   Copyright (C) 2003-2007  University of Manchester
 *
 *   This library is free software; you can redistribute it and/or
 *   modify it under the terms of the GNU Lesser General Public
 *   License as published by the Free Software Foundation; either
 *   version 2.1 of the License, or (at your option) any later version.
 *
 *   This library is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *   Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public
 *   License along with this library; if not, write to the Free Software
 *   Foundation, 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA. 
 *   (or see http://www.gnu.org/copyleft/lesser.html)
 */
package org.openscience.cdk.iupac.parser;

public interface NomParserConstants {

  int EOF = 0;
  int EOL = 1;
  int CONSTANT = 2;
  int DIGIT = 3;
  int DASH = 4;
  int COMMA = 5;
  int METH = 6;
  int ETH = 7;
  int PROP = 8;
  int BUT = 9;
  int UNDEC = 10;
  int EICOS = 11;
  int HENICOS = 12;
  int HEN = 13;
  int DO = 14;
  int TRI = 15;
  int TETR = 16;
  int PENT = 17;
  int HEX = 18;
  int HEPT = 19;
  int OCT = 20;
  int NON = 21;
  int DEC = 22;
  int COS = 23;
  int CONT = 24;
  int A = 25;
  int SPACE = 26;
  int AN = 27;
  int EN = 28;
  int YN = 29;
  int YL = 30;
  int DI = 31;
  int CYCLO = 32;
  int CHLORO = 33;
  int FLUORO = 34;
  int BROMO = 35;
  int IODO = 36;
  int NITRO = 37;
  int OXO = 38;
  int PHENYL = 39;
  int AMINO = 40;
  int ALUMINO = 41;
  int LITHO = 42;
  int HYDROXY = 43;
  int E = 44;
  int OL = 45;
  int OICACID = 46;
  int OYLCHLORIDE = 47;
  int NITRILE = 48;
  int AL = 49;
  int AMIDE = 50;
  int AMINE = 51;
  int ONE = 52;
  int OATE = 53;
  int LITHIUM = 54;
  int SODIUM = 55;
  int POTASSIUM = 56;
  int RUBIDIUM = 57;
  int CESIUM = 58;
  int FRANCIUM = 59;
  int BERYLLIUM = 60;
  int MAGNESIUM = 61;
  int CALCIUM = 62;
  int STRONTIUM = 63;
  int BARIUM = 64;
  int RADIUM = 65;
  int SCANDIUM = 66;
  int YTTRIUM = 67;
  int LANTHANUM = 68;
  int ACTINIUM = 69;
  int TITANIUM = 70;
  int ZIRCONIUM = 71;
  int HAFNIUM = 72;
  int RUTHERFORDIUM = 73;
  int VANADIUM = 74;
  int NIOBIUM = 75;
  int TANTALUM = 76;
  int DUBNIUM = 77;
  int CHROMIUM = 78;
  int MOLYBDENUM = 79;
  int TUNGSTEN = 80;
  int SEABORGIUM = 81;
  int MANGANESE = 82;
  int TECHNETIUM = 83;
  int RHENIUM = 84;
  int BOHRIUM = 85;
  int IRON = 86;
  int RUTHENIUM = 87;
  int OSMIUM = 88;
  int HASSIUM = 89;
  int COBALT = 90;
  int RHODIUM = 91;
  int IRIDIUM = 92;
  int MEITMERIUM = 93;
  int NICKEL = 94;
  int PALLADIUM = 95;
  int PLATINUM = 96;
  int COPPER = 97;
  int SILVER = 98;
  int GOLD = 99;
  int ZINC = 100;
  int CADMIUM = 101;
  int MECURY = 102;
  int ALUMINIUM = 103;
  int GALLIUM = 104;
  int INDIUM = 105;
  int THALLIUM = 106;
  int GERMAINIUM = 107;
  int TIN = 108;
  int LEAD = 109;
  int ARSENIC = 110;
  int ANTIMONY = 111;
  int BISMUTH = 112;
  int SELENIUM = 113;
  int TELLURIUM = 114;
  int POLONIUM = 115;
  int CERIUM = 116;
  int PRASEODYMIUM = 117;
  int NEODYMIUM = 118;
  int PROMETHIUM = 119;
  int SANARIUM = 120;
  int EUROPIUM = 121;
  int GADOLINIUM = 122;
  int TERBIUM = 123;
  int DYSPROSIUM = 124;
  int HOLMIUM = 125;
  int ERBIUM = 126;
  int THULIUM = 127;
  int YTTERBIUM = 128;
  int LUTETIUM = 129;
  int THORIUM = 130;
  int PROTACTINIUM = 131;
  int URANIUM = 132;
  int NEPTUNIUM = 133;
  int PLUTONIUM = 134;
  int AMERCIUM = 135;
  int CURIUM = 136;
  int BERKELIUM = 137;
  int CALIFORNIUM = 138;
  int EINSTEINIUM = 139;
  int FERMIUM = 140;
  int MENDELEVIUM = 141;
  int NOBELIUM = 142;
  int LAWRENCIUM = 143;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<EOL>",
    "<CONSTANT>",
    "<DIGIT>",
    "\"-\"",
    "\",\"",
    "\"meth\"",
    "\"eth\"",
    "\"prop\"",
    "\"but\"",
    "\"undec\"",
    "<EICOS>",
    "\"henicos\"",
    "\"hen\"",
    "\"do\"",
    "\"tri\"",
    "\"tetra\"",
    "\"pent\"",
    "\"hex\"",
    "\"hept\"",
    "\"oct\"",
    "\"non\"",
    "\"dec\"",
    "\"cos\"",
    "\"cont\"",
    "\"a\"",
    "\" \"",
    "\"an\"",
    "\"en\"",
    "\"yn\"",
    "\"yl\"",
    "\"di\"",
    "\"cyclo\"",
    "\"chloro\"",
    "\"fluoro\"",
    "\"bromo\"",
    "\"iodo\"",
    "\"nitro\"",
    "\"oxo\"",
    "\"phenyl\"",
    "\"amino\"",
    "\"alumino\"",
    "\"litho\"",
    "\"hydroxy\"",
    "\"e\"",
    "\"ol\"",
    "\"oic acid\"",
    "\"oyl chloride\"",
    "\"nitrile\"",
    "\"al\"",
    "\"amide\"",
    "\"amine\"",
    "\"one\"",
    "\"oate\"",
    "\"lithium\"",
    "\"sodium\"",
    "\"potassium\"",
    "\"rubidium\"",
    "\"cesium\"",
    "\"francium\"",
    "\"beryllium\"",
    "\"magnesium\"",
    "\"calcium\"",
    "\"strontium\"",
    "\"barium\"",
    "\"radium\"",
    "\"scandium\"",
    "\"yttrium\"",
    "\"lanthanum\"",
    "\"actinium\"",
    "\"titanium\"",
    "\"zirconium\"",
    "\"hafnium\"",
    "\"rutherfordium\"",
    "\"vanadium\"",
    "\"niobium\"",
    "\"tantalum\"",
    "\"dubnium\"",
    "\"chromium\"",
    "\"molybdenum\"",
    "\"tungsten\"",
    "\"seaborgium\"",
    "\"manganese\"",
    "\"technetium\"",
    "\"rhenium\"",
    "\"bohrium\"",
    "\"iron\"",
    "\"ruthenium\"",
    "\"osmium\"",
    "\"hassium\"",
    "\"cobalt\"",
    "\"rhodium\"",
    "\"iridium\"",
    "\"meitmerium\"",
    "\"nickel\"",
    "\"palladium\"",
    "\"platinum\"",
    "\"copper\"",
    "\"silver\"",
    "\"gold\"",
    "\"zinc\"",
    "\"cadmium\"",
    "\"mercury\"",
    "\"aluminium\"",
    "\"gallium\"",
    "\"indium\"",
    "\"thallium\"",
    "\"germainium\"",
    "\"tin\"",
    "\"lead\"",
    "\"arsenic\"",
    "\"antimony\"",
    "\"bismuth\"",
    "\"selenium\"",
    "\"tellurium\"",
    "\"polonium\"",
    "\"cerium\"",
    "\"praseodymium\"",
    "\"neodymium\"",
    "\"promethium\"",
    "\"sanarium\"",
    "\"europium\"",
    "\"gadolinium\"",
    "\"terbium\"",
    "\"dysprosium\"",
    "\"holmium\"",
    "\"erbium\"",
    "\"thulium\"",
    "\"ytterbium\"",
    "\"lutetium\"",
    "\"thorium\"",
    "\"protactinium\"",
    "\"uranium\"",
    "\"neptunium\"",
    "\"plutonium\"",
    "\"amercium\"",
    "\"curium\"",
    "\"berkelium\"",
    "\"californium\"",
    "\"einsteinium\"",
    "\"fermium\"",
    "\"mendelevium\"",
    "\"nobelium\"",
    "\"lawrencium\"",
  };

}
